#
# Your Crowdin credentials
#
"project_id_env" : "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true
#
# Files configuration
#
files: [
  {
    "source" : "/layout-webapp/src/main/resources/locale/portlet/LayoutEditor_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {"_en!": "","ar_SA": "ar","ar_OM": "aro","ca_ES": "ca","co_FR": "co","cs_CZ": "cs","de_DE": "de","el_GR": "el","en_US": "en","es_ES": "es_ES","et_EE": "et","fa_IR": "fa","fi_FI": "fi","fil_PH": "fil","fr_FR": "fr","he_IL": "he","hr_HR": "hr","hu_HU": "hu","id_ID": "id","it_IT": "it","ja_JP": "ja","ko_KR": "ko","lt_LT": "lt","nl_NL": "nl","no_NO": "no","pl_PL": "pl","pt_BR": "pt_BR","pt_PT": "pt_PT","ro_RO": "ro","ru_RU": "ru","sk_SK": "sk","sl_SI": "sl","sq_AL": "sq","sv_SE": "sv_SE","th_TH": "th","tr_TR": "tr","uk_UA": "uk","vi_VN": "vi","zh_CN": "zh_CN","zh_TW": "zh_TW"},
    "dest" : "hub/layout/LayoutEditor.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/layout-webapp/src/main/resources/locale/portlet/SiteManagement_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {"_en!": "","ar_SA": "ar","ar_OM": "aro","ca_ES": "ca","co_FR": "co","cs_CZ": "cs","de_DE": "de","el_GR": "el","en_US": "en","es_ES": "es_ES","et_EE": "et","fa_IR": "fa","fi_FI": "fi","fil_PH": "fil","fr_FR": "fr","he_IL": "he","hr_HR": "hr","hu_HU": "hu","id_ID": "id","it_IT": "it","ja_JP": "ja","ko_KR": "ko","lt_LT": "lt","nl_NL": "nl","no_NO": "no","pl_PL": "pl","pt_BR": "pt_BR","pt_PT": "pt_PT","ro_RO": "ro","ru_RU": "ru","sk_SK": "sk","sl_SI": "sl","sq_AL": "sq","sv_SE": "sv_SE","th_TH": "th","tr_TR": "tr","uk_UA": "uk","vi_VN": "vi","zh_CN": "zh_CN","zh_TW": "zh_TW"},
    "dest" : "hub/layout/SiteManagement.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/layout-webapp/src/main/resources/locale/portlet/SiteNavigation_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {"_en!": "","ar_SA": "ar","ar_OM": "aro","ca_ES": "ca","co_FR": "co","cs_CZ": "cs","de_DE": "de","el_GR": "el","en_US": "en","es_ES": "es_ES","et_EE": "et","fa_IR": "fa","fi_FI": "fi","fil_PH": "fil","fr_FR": "fr","he_IL": "he","hr_HR": "hr","hu_HU": "hu","id_ID": "id","it_IT": "it","ja_JP": "ja","ko_KR": "ko","lt_LT": "lt","nl_NL": "nl","no_NO": "no","pl_PL": "pl","pt_BR": "pt_BR","pt_PT": "pt_PT","ro_RO": "ro","ru_RU": "ru","sk_SK": "sk","sl_SI": "sl","sq_AL": "sq","sv_SE": "sv_SE","th_TH": "th","tr_TR": "tr","uk_UA": "uk","vi_VN": "vi","zh_CN": "zh_CN","zh_TW": "zh_TW"},
    "dest" : "hub/layout/SiteNavigation.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/layout-webapp/src/main/resources/locale/portlet/Analytics_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {"_en!": "","ar_SA": "ar","ar_OM": "aro","ca_ES": "ca","co_FR": "co","cs_CZ": "cs","de_DE": "de","el_GR": "el","en_US": "en","es_ES": "es_ES","et_EE": "et","fa_IR": "fa","fi_FI": "fi","fil_PH": "fil","fr_FR": "fr","he_IL": "he","hr_HR": "hr","hu_HU": "hu","id_ID": "id","it_IT": "it","ja_JP": "ja","ko_KR": "ko","lt_LT": "lt","nl_NL": "nl","no_NO": "no","pl_PL": "pl","pt_BR": "pt_BR","pt_PT": "pt_PT","ro_RO": "ro","ru_RU": "ru","sk_SK": "sk","sl_SI": "sl","sq_AL": "sq","sv_SE": "sv_SE","th_TH": "th","tr_TR": "tr","uk_UA": "uk","vi_VN": "vi","zh_CN": "zh_CN","zh_TW": "zh_TW"},
    "dest" : "hub/layout/Analytics.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
]
